### ISSUE TITLE
Specify number of CPU cores for `tree` process

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/fluflo#3]
The `tree` process uses iqtree's automatic calculation to determine the number of threads to use:

https://github.com/BCCDC-PHL/fluflo/blob/bf94bce2fc9e691fc38d5437eb87bd7a025878fe/main.nf#L117

...but doesn't indicate to the executor (SLURM) how many CPU cores will be used in that process. That results in many more CPU cores being used on the worker node than SLURM is aware of.

Please specify a specific number of CPUs to use in the `tree` process using [task.cpus](https://www.nextflow.io/docs/latest/process.html?highlight=task%20cpus#cpus)

**Comment by j3551ca** [comment]
Thanks for catching. Removed second redundant -T option specifying task.cpus and added to -nt switch instead, so should no longer conflict.
